Add mocks, display offers, add state for the review form
htmlacademy-react/1045065-six-cities-5 pull request #5
Opened 2020-10-20 00:26 UTC by aleksandranichols

Add mocks, display offers, add state for the review form

2020-10-20 02:30 UTC, phwb requested changes

2020-10-20 02:30 UTC, phwb commented on src/components/app.jsx
> +        <Main RENTAL_OFFERS_TOTAL = {RENTAL_OFFERS_TOTAL}
не нужно передавать константы через пропсы, вынеси ее отсюда

2020-10-20 02:30 UTC, phwb commented on src/components/app.jsx
> +        <Main RENTAL_OFFERS_TOTAL = {RENTAL_OFFERS_TOTAL}
если хочешь передать кол-во элементов, которое нужно отрисовать, то назови пропс как-то более понятнее `count`, `length` или еще как-нибудь. но в данном случае этого делать не нужно, просто используй константу

2020-10-20 02:30 UTC, phwb commented on src/components/favorites.jsx
> +                      <a href="#">
`<Link to={'/offer/${offer.id}'}/>` или `i` если `id` нет

2020-10-20 02:30 UTC, phwb commented on src/components/favorites.jsx
> +                        <Link to="/offer/1" href="#">{offer.title}</Link>
тут тоже вместо `1` нужно либо индекс использовать либо айдишник

2020-10-20 02:30 UTC, phwb commented on src/components/favorites.jsx
> +      <Link to="/" className="footer__logo-link" href="main.html">
href убирай

2020-10-20 02:30 UTC, phwb commented on src/components/main.jsx
> +            <b className="places__found">{RENTAL_OFFERS_TOTAL} places to stay in Amsterdam</b>
а так это не константа )) используй `offers.length`

2020-10-20 02:30 UTC, phwb commented on src/components/offer-card.jsx
> +      <a href="#">
Link

2020-10-20 02:30 UTC, phwb commented on src/components/offer.jsx
> +  const offer = props.offers[0];
передавай в пропсах не массив, а один элемент:
```jsx
offers.map(offer => (
  <Offer offer={offer}/>
))
```

2020-10-20 02:30 UTC, phwb commented on src/components/offer.jsx
> +                {offer.reviews.map((review, i) =>
это можно вынести в отдельный компонент

2020-10-21 20:08 UTC, aleksandranichols commented on src/components/favorites.jsx
> +                      <a href="#">
@phwb я то не против, но откуда это кстати взято? Я не видела в требованиях, что клик на картинку ведет на страницу с предложением

2020-10-21 20:12 UTC, aleksandranichols commented on src/components/main.jsx
> +            <b className="places__found">{RENTAL_OFFERS_TOTAL} places to stay in Amsterdam</b>
> а так это не константа )) используй `offers.length`

ну в теории была константой :D

2020-10-22 04:11 UTC, phwb commented on src/components/favorites.jsx
> +                      <a href="#">
ты по любому пользуешься соц сетями, и там есть новости, вот представь что ты кликаешь на картинку, а новость не открывается, сколько тебе нужно попыток чтобы догадаться что нужно кликать по заголовку ))

2020-10-22 04:18 UTC, phwb reviewed
чтобы в каждом компоненте не дублировать шапку и футер, можешь вынести из в отдельные компоненты. или создать компонент Page, где будет шапка и футер, и пользоваться вот так:
```jsx
<Page>
  <Main/>
</Page>
```
в данный момент это делать не обязательно, можешь сделать в будущем

2020-10-22 04:18 UTC, phwb commented on src/components/app.jsx
> +        <Main offers={offers} Offers={Offers} />
зачем ты компонент туда закинула `Offers`, не вижу чтобы он использовался внутри

2020-10-22 04:18 UTC, phwb commented on src/components/offer-card.jsx
> +    onMouseEnter={handleHover}
если событие одно, то лучше используй onHover

2020-10-22 04:18 UTC, phwb commented on src/components/offer-proptypes.jsx
> +const OfferProptypes = () => {
не нужно с большой буквы именовать, это обычная функция, а не конструктор

2020-10-22 04:18 UTC, phwb commented on src/components/review-proptypes.jsx
> +const ReviewProptypes = () => {
именование

2020-10-22 15:33 UTC, aleksandranichols commented on src/components/app.jsx
> +        <Main offers={offers} Offers={Offers} />
> зачем ты компонент туда закинула `Offers`, не вижу чтобы он использовался внутри

он используется в разметке, но зачем я передала его как пропсы я хз, убрала

2020-10-22 15:33 UTC, aleksandranichols commented
> чтобы в каждом компоненте не дублировать шапку и футер, можешь вынести из в отдельные компоненты. или создать компонент Page, где будет шапка и футер, и пользоваться вот так:
> 
> ```js-jsx
> <Page>
>   <Main/>
> </Page>
> ```
> 
> в данный момент это делать не обязательно, можешь сделать в будущем

ага, я думала об этом

2020-10-22 15:34 UTC, aleksandranichols commented on src/components/offer-card.jsx
> +    onMouseEnter={handleHover}
> если событие одно, то лучше используй onHover

их вроде можно и так и так же называть?

2020-10-22 17:03 UTC, aleksandranichols commented on src/components/app.jsx
> +      ))}
Исправила map, иначе на странице с оффером отображались все офферы а не один

2020-10-23 03:56 UTC, aleksandranichols commented on src/components/offer-card.jsx
> +class OfferCard extends PureComponent {
Пришлось переместить стейт onHover, иначе он не был уникальный для каждого предложения

2020-10-23 05:11 UTC, phwb commented on src/components/offer-card.jsx
> +    onMouseEnter={handleHover}
onHover это комбинация этих двух событий

2020-10-23 05:17 UTC, phwb requested changes

2020-10-23 05:17 UTC, phwb commented on src/components/app.jsx
> +      ))}
воу-воу, по легче ) это делается проще:
```jsx
<Route path={`/offer/:id`} component={Offer}/>
```
потом в компоненте Offer будет доступен просп `match.params.id`.
или можно по другому:
```jsx
<Route path={`/offer/:id`} render={(props) => {
  const offer = offers.find(o => o.id === props.match.params.id)
  return <Offer offer={offer}/>
}}/>
```

2020-10-23 05:17 UTC, phwb commented on src/components/offer-card.jsx
> +      onMouseLeave={this._onHover}>
не нужно два события, пользуйся onHover

2020-10-26 04:34 UTC, phwb approved these changes

2020-10-26 04:36 UTC, merged